### PR TITLE
make align columns

### PR DESCRIPTION
**Pull request by amird308**
a little feature for make align columns

### CODE REVIEW

**Comment by amird308** [comment]
```
<Masonry alignColumns={true} columnsCount={3} gutter="10px">
          {images.map((image, i) => (
            <img
              key={i}
              src={image}
              // set height of style form heights array randomly
              style={{width: "100%", display: "block", height: [number]}}
            />
          ))}
        </Masonry>
```

now you have align columns

**Comment by amird308** [comment]
if you have a image higher than other like this case:

Screenshot 2023-10-29 at 3 30 35 PM

without alignColumns:

Screenshot 2023-10-29 at 3 31 13 PM

with alignColumns:

Screenshot 2023-10-29 at 3 30 47 PM

**Comment by Amit-Dagar** [comment]
what if someone doesn't have height data with images ?

**Comment by gabrielmicko** [comment]
If I see it correctly, this library did not calculate the height of each children, but rather just splits children equally into separate columns. Probably this works for most of the people, but not for me. I end up with large column differences.

**Comment by cedricdelpoux** [comment]
Sorry, I missed your PR. Could you rebase? I will merge and publish it. Thanks

**Comment by amird308** [comment]
> Sorry, I missed your PR. Could you rebase? I will merge and publish it. Thanks

`

**Comment by cedricdelpoux** [comment]
@amird308 There are still conflicts and I can't merge. Could you rebase please?

**Pull request closed without merging**
